---
- hosts: all
  remote_user: centos
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
   - name: Add group "ansibleadmins" to remote server
     group:
       name: ansibleadmin
       gid: 2010
       state: present

   - name: Add user "sudouser" to remote server
     user:
       name: ansible
       comment: "Privileged User"
       uid: 2001
       group: ansibleadmin
       append: yes
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

...
