- name: Create IP address
  hosts: localhost
  gather_facts: no

  vars:
    service_account_file: /tmp/key_pair/gothic-sylph-318919-bd11b38ccb2a.json
    project: My First Project
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:

   - name: Allocate an IP Address
     gcp_compute_address:
         state: present
         name: 'test-address1'
         region: 'us-eact4'
         project: "{{ project }}"
         auth_kind: "{{ auth_kind }}"
         service_account_file: "{{ service_account_file }}"
         scopes: "{{ scopes }}"
