--- 
- 
  hosts: localhost
  name: "Create a GCP instance"
  tasks: 
    - 
      gcp_compute_disk: 
        auth_kind: "{{ gcp_cred_kind }}"
        name: disk-instance
        project: "{{ gcp_project }}"
        size_gb: 20
        source_image: projects/gothic-sylph-318919/global/images/rhel-8
        state: present
        zone: us-east4-c
      name: "create a disk mapped from RHEL8 image"
      register: disk
    - 
      gcp_compute_network: 
        auth_kind: "{{ gcp_cred_kind }}"
        name: network-instance
        project: "{{ gcp_project }}"
        state: present
      name: "create a  VPC network"
      register: network
    - 
      gcp_compute_address: 
        auth_kind: "{{ gcp_cred_kind }}"
        name: address-instance
        project: "{{ gcp_project }}"
        region: us-east4
        state: present
      name: "create an IPv4 public IP Address"
      register: address
    - 
      gcp_compute_instance: 
        auth_kind: "{{ gcp_cred_kind }}"
        disks: 
          - 
            auto_delete: "true"
            boot: "true"
            source: "{{ disk }}"
        machine_type: n1-standard-1
        name: rhel8
        network_interfaces: 
          - 
            access_configs: 
              - 
                name: "External NAT"
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
            network: "{{ network }}"
        project: "{{ gcp_project }}"
        state: present
        zone: us-east4-c
      name: "create the RHEL8 instance"
    - 
      debug: 
        msg: "The RHEL8 instance is accessible at {{ address.address }}"
      name: "Show RHEL8 Instance Details"
  vars: 
    gcp_cred_kind: serviceaccount
    gcp_project: gothic-sylph-318919
