--- 
- 
  gather_facts: false
  hosts: localhost
  name: "Create Instances in GCE"
  tasks: 
    - 
      gce: 
        disk_size: "{{disk_size}}"
        image: "{{image}}"
        instance_names: "{{instance_names}}"
        machine_type: "{{machine_type}}"
        preemptible: true
        state: present
        tags: "http-server,https-server,cockpit-console"
        zone: "{{zone}}"
      name: "Create an Instance based on image \"{{image}}\""
      register: gce
    - 
      gce_pd: 
        delete_on_termination: true
        instance_name: "{{instance_names}}"
        mode: READ_WRITE
        name: vg-ocp
        size_gb: 20
        state: present
        zone: "{{zone}}"
      name: "Add disk to Instance"
    - 
      add_host: 
        groupname: gce_instances_temp
        hostname: "{{ item.public_ip }}"
      name: "Save host data within a Group"
      with_items: "{{ gce.instance_data }}"
    - 
      name: "Wait for SSH to come up"
      wait_for: "host={{ item.public_ip }} port=22 delay=10 timeout=60"
      with_items: "{{ gce.instance_data }}"
    - 
      name: "setting fact"
      set_fact: "host={{ item.public_ip }}"
      with_items: "{{ gce.instance_data }}"
    - ~
  vars: 
    disk_size: 10
    image: projects/gothic-sylph-318919/global/images/rhel-8
    instance_names: ansible-workshop-instance
    machine_type: g1-small
    zone: us-east4-c
